/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg16111100094_rahmatsetiawan_input;

import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.scene.input.DataFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author RAHMAT SETIAWAN 16111100094-16B
 */
public class tampil extends javax.swing.JFrame {
    //memanggil variabel dari pengguna_sesi.java
    int id_user = pengguna_sesi.getU_id_user();
    String username = pengguna_sesi.getU_username();
    String password = pengguna_sesi.getU_password();
    String nama_lengkap = pengguna_sesi.getU_nama_lengkap();
    String email = pengguna_sesi.getU_email();
    String level_pengguna = pengguna_sesi.getU_level_pengguna();
    String status_pengguna = pengguna_sesi.getU_status_pengguna();
 
    /**
     * Creates new form FrmMenu
     */

    
    
    private Object conn;

    /**
     * Creates new form tampil
     */
    public tampil() {
        initComponents();
        //memanggil klaas load data;
        tabel_data ();
        form_kosong ();
        
        //menampilkan sesi pengguna
        tampil_sesi.setText("Nama Pengguna: " +nama_lengkap+"       /Email: "+email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isian_jenis_kelamin1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isian_nim = new javax.swing.JTextField();
        isian_nama = new javax.swing.JTextField();
        isian_alamat = new javax.swing.JTextField();
        isian_phone = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        laki_laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        isian_prodi1 = new javax.swing.JComboBox<>();
        isian_tgl_lahir1 = new org.jdesktop.swingx.JXDatePicker();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tampil_sesi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Prodi", "Alamat", "Phone"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Phone");

        isian_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isian_alamatActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel5.setText("Tgl Lahir");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Prodi");

        isian_jenis_kelamin1.add(laki_laki);
        laki_laki.setText("Laki-Laki");
        laki_laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laki_lakiActionPerformed(evt);
            }
        });

        isian_jenis_kelamin1.add(perempuan);
        perempuan.setText("Perempuan");
        perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanActionPerformed(evt);
            }
        });

        isian_prodi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Akuntansi", "Pend. B. Indonesia", "Pend. B. Inggris" }));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isian_nim)
                            .addComponent(isian_nama)
                            .addComponent(isian_tgl_lahir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(laki_laki, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(isian_prodi1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isian_alamat)
                            .addComponent(isian_phone)))
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(isian_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isian_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isian_tgl_lahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(laki_laki)
                    .addComponent(perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(isian_prodi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isian_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isian_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpan)
                .addContainerGap())
        );

        tampil_sesi.setText("nama Pengguna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tampil_sesi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampil_sesi)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void isian_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isian_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isian_alamatActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
try {
    //pengaturan format tanggal pada tanggal lahir;
    Date oDate = isian_tgl_lahir1.getDate();
    DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tgllahir = oDateFormat.format(oDate);
    //pilihan jenis kelamin dengan radio buuton;
    String jenis_kelamin = "";
    if(laki_laki.isSelected()){
        jenis_kelamin="laki-laki";
    }else {
        jenis_kelamin="perempuan";
    }
    
    //memasukkan data ke database;
    String sql = "INSERT INTO mhs VALUE('"+
            isian_nim.getText()+"','"+
            isian_nama.getText()+"','"+
            isian_alamat.getText()+"','"+
            isian_phone.getText()+"','"+
            tgllahir+"','"+
            jenis_kelamin+"','"+
            isian_prodi1.getSelectedItem()+"')";
    java.sql.Connection conn= (Connection) config.configDB();
    java.sql.PreparedStatement pst=conn.prepareStatement (sql);
    pst.execute();
    JOptionPane.showMessageDialog(null, "penyimpanan berhasil brow");
    tabel_data ();  //memanggil class tabel_data;
    form_kosong (); 
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_simpanActionPerformed
//menampilkan data dari database ke tabel;
private void tabel_data( ){
     //memberi penamaan pada judul kolom tabel;    
    DefaultTableModel model = new DefaultTableModel ( );
             tabel1.setModel(model);
             model.addColumn("NIM");
             model.addColumn("Nama");
             model.addColumn("Tanggal lahir");
             model.addColumn("Jenis Kelamin");
             model.addColumn("Prodi"); 
             model.addColumn("Alamat");
             model.addColumn("Phone");
try {
     //mengambil data dari database;
    String sql = "SELECT * from mhs";
    java.sql.Connection conn=(Connection) config.configDB();
    java.sql.Statement stm=conn.createStatement();
    java.sql.ResultSet res=stm.executeQuery(sql);
    while (res.next()) {
        model.addRow(new Object[]{
            res.getString(1),
            res.getString(2),
            res.getString(5), 
            res.getString(6), 
            res.getString(7), 
            res.getString(3), 
            res.getString(4)});
    }
    tabel1.setModel (model);
}catch (Exception e){
}
}

private void form_kosong (){
            isian_nim.setText("");
            isian_nama.setText("");
            isian_alamat.setText("");
            isian_phone.setText("");
            isian_tgl_lahir1.setDate(null);
            isian_jenis_kelamin1.clearSelection();
            isian_prodi1.setSelectedIndex(0);
}
    
    private void laki_lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laki_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laki_lakiActionPerformed

    private void perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        int kolom = tabel1.rowAtPoint(evt.getPoint());
        String kolom_nim = tabel1.getValueAt(kolom, 0).toString();
        isian_nim.setText(kolom_nim);
        String kolom_nama = tabel1.getValueAt(kolom, 1).toString();
        isian_nama.setText(kolom_nama);
        
        String kolom_tgl_lahir = tabel1.getValueAt(kolom, 2).toString();
        java.util.Date isian_tgl_lahir = null;
        try {
        isian_tgl_lahir = new SimpleDateFormat ("yyyy-MM-dd").parse(kolom_tgl_lahir);}
        catch (ParseException ex){
        }
        isian_tgl_lahir1.setDate(isian_tgl_lahir);
        
        String kolom_jenis_kelamin = tabel1.getValueAt(kolom, 3).toString();
        if(kolom_jenis_kelamin.equals("laki-laki")){
            laki_laki.setSelected(true);
        }
        if(kolom_jenis_kelamin.equals("perempuan")){
            perempuan.setSelected(true);
        }        
        String kolom_prodi = tabel1.getValueAt(kolom, 4).toString();
        isian_prodi1.setSelectedItem(kolom_prodi);
        String kolom_alamat = tabel1.getValueAt(kolom, 5).toString();
        isian_alamat.setText(kolom_alamat);
        String kolom_phone = tabel1.getValueAt(kolom, 6).toString();
        isian_phone.setText(kolom_phone);        
    }//GEN-LAST:event_tabel1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
try {   
//pengaturan format tanggal pada tanggal lahir;
    Date oDate = isian_tgl_lahir1.getDate();
    DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tgllahir = oDateFormat.format(oDate);
    //pilihan jenis kelamin dengan radio buuton;
    String jenis_kelamin = "";
    if(laki_laki.isSelected()){
        jenis_kelamin="laki-laki";
    }else {
        jenis_kelamin="perempuan";
    }
    
    //memasukkan data ke database;
    String sql = "UPDATE mhs SET nim='"+
            isian_nim.getText()+"',nama='"+
            isian_nama.getText()+"',alamat='"+
            isian_alamat.getText()+"',telp='"+
            isian_phone.getText()+"',tgl_lahir='"+
            tgllahir+"',jenis_kelamin='"+
            jenis_kelamin+"',prodi='"+
            isian_prodi1.getSelectedItem()+
            "'WHERE nim ='"+isian_nim.getText()+"'";
    java.sql.Connection conn= (Connection) config.configDB();
    java.sql.PreparedStatement pst=conn.prepareStatement (sql);
    pst.execute();
    JOptionPane.showMessageDialog(null, "perubahan data berhasil brow");
    tabel_data ();  //memanggil class tabel_data;
    form_kosong (); 
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
                  
  
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
try {   
    
    //memasukkan data ke database;
    String sql = "DELETE FROM mhs WHERE nim ='"+isian_nim.getText()+"'";
    java.sql.Connection conn= (Connection) config.configDB();
    java.sql.PreparedStatement pst=conn.prepareStatement (sql);
    pst.execute();
    JOptionPane.showMessageDialog(null, "hapus data berhasil brow");
    tabel_data ();  //memanggil class tabel_data;
    form_kosong (); 
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}        
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField isian_alamat;
    private javax.swing.ButtonGroup isian_jenis_kelamin1;
    private javax.swing.JTextField isian_nama;
    private javax.swing.JTextField isian_nim;
    private javax.swing.JTextField isian_phone;
    private javax.swing.JComboBox<String> isian_prodi1;
    private org.jdesktop.swingx.JXDatePicker isian_tgl_lahir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton laki_laki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel1;
    private javax.swing.JLabel tampil_sesi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    }
